### PR TITLE
Additional formatting changes

### PR DESCRIPTION
**Pull request by defaziogiancarlo**
Made all quotes double quotes.
Alphabetized the imports.
Made all regex strings raw.

### CODE REVIEW

**Comment by ofaaland** [comment]
What is the motivation for this?  Did one of our style-checking tools (other than black) prompt this?

**Comment by defaziogiancarlo** [comment]
For the quotes, it's because I used the `-S` flag for `black` which skipped setting a consistent quote type. I reformatted without using  `-S`. The dict `colors` in the original version has both single and double quotes for no apparent reason.

For alphabetizing the imports I might be thinking of another programming language, or the Google python style guide.
That's not in the Python style guide or LC's guide.

For the regex strings that really is a potential bug, and it was caught as a syntax error by the tool `flake8`.
```
llogcolor:71:21: W605 invalid escape sequence '\d'
```
Meaning that only the first line of the regex is a raw string. I'm very confident that the entire regex was meant to be a raw string.

**Comment by ofaaland** [comment]
OK, please break this up into two commits.  One that you believe to be entirely stylistic and have no semantic implications, and one for the regex string issue caught by flake8.  You can use this same PR.  Make sure for each commit, the commit message gives the motivation please.  Thanks!

**Comment by defaziogiancarlo** [comment]
Making new pull request with multiple smaller commits.

**Pull request closed without merging**
